config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/search', to: 'home#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

# Wrappepr to make Ruby objects for Openweathermap weather details
class City
  NOT_FOUND = '404'

  # @params details [Hash]
  def initialize(details)
    @details = details

    @coordinates = Coordinates.new(details['coord'])
    @weather = Weather.new(
      details['weather'],
      details['wind'],
      details['snow'],
      details['rain'],
      details['cloud']
    )
    @temperature = Temperature.new(details['main'])
  end

  delegate :latitude, :longitude, to: :coordinates

  delegate :humanized_weather_conditions,
           :primary_humanized_weather,
           :weather_icons,
           :primary_weather_icon,
           :wind_speed,
           :wind_direction,
           :wind_gust,
           :cloudiness,
           :last_1_hour_rain,
           :last_3_hour_rain,
           :last_1_hour_snow,
           :last_3_hour_snow,
           to: :weather

  delegate :minimum,
           :maximum,
           :current,
           to: :temperature, prefix: true

  delegate :feels_like,
           :humidity,
           :pressure,
           :sea_level_pressure,
           :ground_level_pressure,
           to: :temperature

  def name
    details['name']
  end

  def country_code
    details.dig('sys', 'country')
  end

  def sunrise_time
    Time.zone.at(details.dig('sys', 'sunrise') + timezone_shift)
  end

  def sunset_time
    Time.zone.at(details.dig('sys', 'sunset') + timezone_shift)
  end

  def visibility
    details['visibility']
  end

  def timezone_shift
    details['timezone']
  end

  def not_found?
    details['cod'] == NOT_FOUND
  end

  def error_message
    details['message']
  end

  private

  attr_reader :details, :weather, :temperature, :coordinates
end

app/models/city/coordinates.rb
# frozen_string_literal: true

class City
  # Coordinates details for the city
  class Coordinates
    def initialize(coordinates_details)
      @coordinates_details = coordinates_details
    end

    def latitude
      coordinates_details['lat']
    end

    def longitude
      coordinates_details['lon']
    end

    private

    attr_reader :coordinates_details
  end
end

app/models/city/temperature.rb
# frozen_string_literal: true

class City
  # Temperature details for the city
  class Temperature
    # @params temperature_details [Hash]
    def initialize(temperature_details)
      @temperature_details = temperature_details
    end

    def minimum
      temperature_details['temp_min']
    end

    def maximum
      temperature_details['temp_max']
    end

    def current
      temperature_details['temp']
    end

    def feels_like
      temperature_details['feels_like']
    end

    def humidity
      temperature_details['humidity']
    end

    def pressure
      temperature_details['pressure']
    end

    def sea_level_pressure
      temperature_details['sea_level']
    end

    def ground_level_pressure
      temperature_details['grnd_level']
    end

    private

    attr_reader :temperature_details
  end
end

app/models/city/weather.rb
# frozen_string_literal: true

class City
  # General weather details for the city
  class Weather
    # @params weather [Hash]
    # @params wind [Hash]
    # @params snow [Hash]
    # @params rain [Hash]
    # @params cloud [Hash]
    def initialize(weather, wind, snow, rain, cloud)
      @weather = weather
      @wind = wind
      @snow = snow
      @rain = rain
      @cloud = cloud
    end

    def humanized_weather_conditions
      weather.map { |details| details['main'] }
    end

    def primary_humanized_weather
      humanized_weather_conditions.first
    end

    def weather_icons
      weather.map { |details| details['icon'] }
    end

    def primary_weather_icon
      weather_icons.first
    end

    def wind_speed
      wind['speed']
    end

    def wind_direction
      wind['deg']
    end

    def wind_gust
      wind['gust']
    end

    def cloudiness
      cloud['all']
    end

    def last_1_hour_rain
      rain&.fetch('1h')
    end

    def last_3_hour_rain
      rain&.fetch('3h')
    end

    def last_1_hour_snow
      snow&.fetch('1h')
    end

    def last_3_hour_snow
      snow&.fetch('3h')
    end

    private

    attr_reader :weather, :wind, :rain, :snow, :cloud
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# HomeControllerEntryPoint for our App
class HomeController < ApplicationController
  def index; end

  def search
    redirect_to root_path unless params[:query].present?

    details = Openweathermap::ApiWrapper.new.current_weather_for(params[:query])
    @city = City.new(details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2>Welcome to weather App</h2>

app/views/home/search.html.erb
<% if @city.not_found? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= @city.error_message %>
  </div>
<% else %>
  <% city_presenter = CityPresenter.new(@city) %>
  <div class="container">
    <div class="card text-center">
      <div class="card-header">
        Weather Details
      </div>
      <div class="card-body">
        <h5 class="card-title">
          <%= city_presenter.name_with_country %>
        </h5>
        <div class="card-text">
          <%= image_tag city_presenter.weather_icon_src %>
          <%= city_presenter.formatted_temperature(@city.temperature_current) %>
        </div>
        <div class="card-text">
          <span>
            Feels Like <%= city_presenter.formatted_temperature(@city.feels_like) %>.
            <%= @city.humanized_weather_conditions.join(', ') %>
          </span>
        </div>
      </div>
      <div class="card-footer text-light">
        <div class="container">
          <span class="badge bg-dark">
            Wind <%= @city.wind_speed %> m/s <%= city_presenter.formatted_wind_direction %>
          </span>
          <span class="badge bg-dark">
            Pressure <%= city_presenter.formatted_pressure @city.pressure %>
          </span>
          <span class="badge bg-dark">
            Humidity <%= city_presenter.formatted_humidity @city.humidity %>
          </span>
        </div>
        <div class="container">
          <span class="badge bg-dark">
            Sunrise <%= city_presenter.formatted_sunrise_time %>
          </span>
          <span class="badge bg-dark">
            Sunset <%= city_presenter.formatted_sunset_time %>
          </span>
          <span class="badge bg-dark">
            Visibility <%= city_presenter.formatted_visibility %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container-fluid'>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
          <%= image_tag "logo.png", class: 'navbar-icon bg-dark' %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
             WEATHER APP
            </li>
          </ul>
          <%= form_with url: search_path, method: :get, class: 'form-inline my-2 my-lg-0', local: true do |form| %>
            <%= text_field_tag 'query', params['query'], class: 'form-control mr-sm-2', type: 'search', placeholder: 'Search', data: { 'aria-label' => 'Search' } %>
            <%= form.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0' %>
          <% end %>
        </div>
      </nav>

      <div class='container-fluid'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>